<?php

namespace ApplianceBundle\Repository;

/**
 * ApplianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplianceRepository extends \Doctrine\ORM\EntityRepository
{
}
